package io.vulpine.lib.query.util;

import java.sql.ResultSet;

/**
 * <code>ReadResult</code> defines the type of a query result object containing
 * a value generated from a call to {@link ReadQuery#execute()}.
 *
 * @param <V> Type of the value contained in this result.
 * @param <Q> The specific type of the {@link ReadQuery} implementation that
 *            created this result.
 */
public interface ReadResult < V, Q extends ReadQuery < ?, ?, ? > >
extends QueryResult < Q >
{
  /**
   * Returns the value generated by parsing the {@link ResultSet} from the
   * executed query.
   *
   * @return value generated from the query execution.
   */
  V getValue();
}
